In [ ]:
import pandas as pd
import numpy as np 
#load data
df=pd.read_csv("../data/cleaned_sales_data.csv")
df.head()

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,main_category,sub_category
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,399.0,1099.0,64.0,4.2,24269,Computers & Accessories,Accessories & Peripherals
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,199.0,349.0,43.0,4.0,43994,Computers & Accessories,Accessories & Peripherals
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,199.0,1899.0,90.0,3.9,7928,Computers & Accessories,Accessories & Peripherals
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,329.0,699.0,53.0,4.2,94363,Computers & Accessories,Accessories & Peripherals
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,154.0,399.0,61.0,4.2,16905,Computers & Accessories,Accessories & Peripherals

In [2]:
df.shape
df.columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1383 entries, 0 to 1382
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1383 non-null   str
 1   product_name         1383 non-null   str
 2   discounted_price     1383 non-null   float64
 3   actual_price         1383 non-null   float64
 4   discount_percentage  1383 non-null   float64
 5   rating               1383 non-null   float64
 6   rating_count         1383 non-null   int64
 7   main_category        1383 non-null   str
 8   sub_category         1383 non-null   str
dtypes: float64(4), int64(1), str(4)
memory usage: 97.4 KB

In [3]:
df.isnull().sum()

product_id             0
product_name           0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
main_category          0
sub_category           0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1383.000000,1383.000000,1383.000000,1383.000000,1383.000000
mean,3260.688937,5661.258337,47.178597,4.092697,18528.794649
std,7106.243584,11121.709243,21.667746,0.295009,43744.375528
min,39.000000,39.000000,0.000000,2.000000,0.000000
25%,348.500000,899.000000,31.000000,4.000000,1168.000000
50%,889.000000,1750.000000,49.000000,4.100000,4971.000000
75%,2123.500000,4699.000000,63.000000,4.300000,17271.500000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

In [6]:
df.nunique()

product_id             1350
product_name           1336
discounted_price        550
actual_price            449
discount_percentage      92
rating                   25
rating_count           1143
main_category             9
sub_category             29
dtype: int64