In [ ]:
import pandas as pd

df=pd.read_csv("../data/cleaned_sales_data.csv")

In [2]:
import matplotlib.pyplot as plt
df['estimated_revenue'] = df['discounted_price'] * df['rating_count']

In [3]:
risk_products = df[(df['rating'] < 3.5) & (df['rating_count'] > df['rating_count'].median())]

risk_products[['product_name', 'main_category', 'rating', 'rating_count']].sort_values(by='rating').head(10)

,product_name,main_category,rating,rating_count
45,Wecool Nylon Braided Multifunction Fast Chargi...,Computers & Accessories,3.3,9792
814,LS LAPSTER Quality Assured Universal Silicone ...,Computers & Accessories,3.3,5692
955,PRO365 Indo Mocktails/Coffee Foamer/Cappuccino...,Home & Kitchen,3.3,8427
700,"Zebronics ZEB-90HB USB Hub, 4 Ports, Pocket Si...",Computers & Accessories,3.4,9385
859,Canon PIXMA MG2577s All-in-One Inkjet Colour P...,Computers & Accessories,3.4,12185

Some products have high demand but low ratings, which shows a potential business risk.  
Many of these products belong to Computers & Accessories, suggesting possible quality or usability issues in this category.

In [4]:
category_summary = df.groupby('main_category').agg({
    'estimated_revenue': 'sum',
    'rating': 'mean',
    'rating_count': 'sum'
}).sort_values(by='estimated_revenue', ascending=False)

                         estimated_revenue    rating  rating_count
main_category
Electronics                   5.858578e+10  4.080354      15560564
Home & Kitchen                6.262254e+09  4.040716       2990077
Computers & Accessories       6.071868e+09  4.151928       6806911
MusicalInstruments            6.445808e+07  3.900000         88882
OfficeProducts                4.578673e+07  4.309677        149675
Health & PersonalCare         3.293037e+06  4.000000          3663
Car & Motorbike               2.615002e+06  3.800000          1118
HomeImprovement               2.587190e+06  4.250000          8566
Toys & Games                  2.380050e+06  4.300000         15867

Electronics generates the highest revenue and demand, but its average rating is lower than some smaller categories.  
This indicates a strong opportunity to improve product quality in the most important business segment.

In [5]:
high_rating_low_revenue = category_summary[(category_summary['rating'] > category_summary['rating'].median())]

high_rating_low_revenue.sort_values(by='estimated_revenue', ascending=True)

                         estimated_revenue    rating  rating_count
main_category
Toys & Games                  2.380050e+06  4.300000         15867
HomeImprovement               2.587190e+06  4.250000          8566
OfficeProducts                4.578673e+07  4.309677        149675
Computers & Accessories       6.071868e+09  4.151928       6806911

Some smaller categories have higher average ratings but lower revenue.  
These categories may represent growth opportunities, as customers already show strong satisfaction and trust.

In [8]:
over_discount = df[df['discount_percentage'] > 80]

over_discount[['product_name', 'main_category', 'discount_percentage', 'rating', 'rating_count']].head(10)

,product_name,main_category,discount_percentage,rating,rating_count
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers & Accessories,90.0,3.9,7928
5,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers & Accessories,85.0,3.9,24871
35,pTron Solero MB301 3A Micro USB Data & Chargin...,Computers & Accessories,85.0,3.9,24871
62,Lapster 1.5 mtr USB 2.0 Type A Male to USB A M...,Computers & Accessories,86.0,4.0,1313
109,PTron Solero T241 2.4A Type-C Data & Charging ...,Computers & Accessories,88.0,3.9,24871
118,"Lapster 5 pin mini usb cable, usb b cable,came...",Computers & Accessories,85.0,4.0,1313
167,Electvision Remote Control Compatible with Kod...,Electronics,83.0,4.0,343
200,Caldipree Silicone Case Cover Compatible for 2...,Electronics,82.0,4.3,407
217,Posh 1.5 Meter High Speed Gold Plated HDMI Mal...,Electronics,83.0,4.3,1237
227,Rts™ High Speed 3D Full HD 1080p Support (10 M...,Electronics,88.0,4.2,910

In [9]:
over_discount.shape[0]

54

Products with extremely high discounts do not show the highest demand and tend to have slightly lower ratings.  
This suggests that excessive discounting may reduce customer trust or reflect weaker product quality.

In [10]:
opportunity_products = df[(df['rating'] >= 4.3) & (df['rating_count'] > df['rating_count'].median())]

opportunity_products[['product_name', 'main_category', 'rating', 'rating_count', 'estimated_revenue']] \
.sort_values(by='estimated_revenue', ascending=False) \
.head(10)

,product_name,main_category,rating,rating_count,estimated_revenue
332,MI 138.8 cm (55 inches) 5X Series 4K Ultra HD ...,Electronics,4.3,21252,998822748.0
231,MI 108 cm (43 inches) 5X Series 4K Ultra HD LE...,Electronics,4.3,21252,680042748.0
405,"OnePlus Nord 2T 5G (Jade Fog, 12GB RAM, 256GB ...",Electronics,4.3,17415,592092585.0
393,"iQOO Neo 6 5G (Dark Nova, 8GB RAM, 128GB Stora...",Electronics,4.4,20311,588998689.0
41,Mi 108 cm (43 inches) Full HD Android LED TV 4...,Electronics,4.3,27151,542992849.0
339,"OnePlus Nord 2T 5G (Jade Fog, 8GB RAM, 128GB S...",Electronics,4.3,17415,505017585.0
340,"OnePlus Nord 2T 5G (Gray Shadow, 8GB RAM, 128G...",Electronics,4.3,17415,505017585.0
249,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,Electronics,4.7,5935,462870650.0
871,"SanDisk 1TB Extreme Portable SSD 1050MB/s R, 1...",Computers & Accessories,4.4,41398,430083822.0
321,Mi 80 cm (32 inches) HD Ready Android Smart LE...,Electronics,4.3,27508,412592492.0

Products with both high ratings and high demand represent strong growth opportunities.  
These products can be prioritized for promotion, inventory planning, and category expansion.

### Final Business Risks and Opportunities

This analysis highlights that some high-demand products have lower ratings, which creates a risk for customer trust and long-term retention.  
The Electronics category is the strongest revenue driver, but its ratings are lower than some smaller categories, showing a clear opportunity for quality improvement in the most important segment.  
At the same time, smaller categories like Office Products and Toys & Games have strong customer satisfaction, which suggests growth potential if promoted further.  
Very high discounts (80%+) do not appear to improve demand significantly and may reduce customer confidence, indicating a pricing risk.  
Overall, the best strategy is to improve quality in high-revenue categories, avoid excessive discounting, and scale highly rated products that already show strong demand.